name: Docker

on:
 workflow_call:

jobs:
 docker:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Docker Login 
      uses: docker/login-action@v2.0.0 
      with: 
        username: luisffilho
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker images
  # You may pin to the exact commit or the version.
  # uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
      uses: docker/build-push-action@v5.1.0
      with:
       context: .
       file: ./Dockerfile
       push: true
       tags: luisffilho/dev-pay-api:${{github.ref_name}}